import { storiesOf } from "@storybook/vue3";
import Questions from "./index";

storiesOf("Questions", module).add("Questions!", () => ({
    components: { Questions },
    data() {
        return {
            errors: {
                1463: "this field is requroed",
            },
            questions: [{
                    id: 1463,
                    value: "This is value!",
                    type: "text",
                    required: true,
                    label: "Name Title",
                    information: "",
                    text_transform: null,
                    text_min_char: null,
                    text_max_char: null,
                    textarea_rows: 2,
                    textarea_min_char: null,
                    textarea_max_char: null,
                    number_initial: null,
                    number_min: null,
                    number_max: null,
                    number_step_count: 5,
                    file_accept_image: false,
                    file_accept_text: false,
                    file_accept_spreadsheet: false,
                    file_accept_presentation: false,
                    file_accept_compressed: false,
                    checkbox_other_option: false,
                    radio_other_option: false,
                    select_multiple: false,
                    information_icon: null,
                    order: 1,
                },
                // {
                //     id: 1464,
                //     value: "",
                //     type: "tel",
                //     required: false,
                //     label: "Mobile Phone",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 2,
                // },
                // {
                //     id: 1465,
                //     value: "",
                //     type: "textarea",
                //     required: false,
                //     label: "Address Line",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 5,
                //     textarea_min_char: 0,
                //     textarea_max_char: 99999,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 3,
                // },
                // {
                //     id: 1466,
                //     value: "",
                //     type: "country",
                //     required: false,
                //     label: "Country",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 4,
                // },
                // {
                //     id: 1467,
                //     value: "",
                //     type: "information",
                //     required: false,
                //     label: "hey!!",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: "info",
                //     order: 5,
                // },
                // {
                //     id: 1468,
                //     value: "",
                //     type: "email",
                //     required: false,
                //     label: "Email",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 6,
                // },
                // {
                //     id: 1469,
                //     value: "",
                //     type: "file",
                //     required: false,
                //     label: "File Upload",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: true,
                //     file_accept_text: true,
                //     file_accept_spreadsheet: true,
                //     file_accept_presentation: true,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 7,
                // },
                // {
                //     id: 1470,
                //     value: "",
                //     type: "checkbox",
                //     required: false,
                //     label: "Multiple Choice Question",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 8,
                //     event_form_field_options: [{
                //             id: 8771,
                //             value: "",
                //             label: "Option 1",
                //             checked: true,
                //             order: 1,
                //             event_form_fields: [],
                //         },
                //         {
                //             id: 8772,
                //             value: "",
                //             label: "Option 2",
                //             checked: false,
                //             order: 2,
                //             event_form_fields: [],
                //         },
                //     ],
                // },
                // {
                //     id: 1471,
                //     value: "",
                //     type: "radio",
                //     required: false,
                //     label: "Single Choice Question",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 9,
                //     event_form_field_options: [{
                //             id: 8773,
                //             value: "",
                //             label: "Option 1",
                //             checked: false,
                //             order: 1,
                //             event_form_fields: [],
                //         },
                //         {
                //             id: 8774,
                //             value: "",
                //             label: "Option 2",
                //             checked: false,
                //             order: 2,
                //             event_form_fields: [],
                //         },
                //     ],
                // },
                // {
                //     id: 1472,
                //     value: "",
                //     type: "select",
                //     required: false,
                //     label: "Dropdown Menu",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 10,
                //     event_form_field_options: [{
                //             id: 8775,
                //             value: "",
                //             label: "Option 1",
                //             checked: false,
                //             order: 1,
                //             event_form_fields: [],
                //         },
                //         {
                //             id: 8776,
                //             value: "",
                //             label: "Option 2",
                //             checked: false,
                //             order: 2,
                //             event_form_fields: [],
                //         },
                //     ],
                // },
                // {
                //     id: 1473,
                //     value: "",
                //     type: "datepicker",
                //     required: false,
                //     label: "Date Picker",
                //     information: "",
                //     text_transform: null,
                //     text_min_char: null,
                //     text_max_char: null,
                //     textarea_rows: 2,
                //     textarea_min_char: null,
                //     textarea_max_char: null,
                //     number_initial: null,
                //     number_min: null,
                //     number_max: null,
                //     number_step_count: 5,
                //     file_accept_image: false,
                //     file_accept_text: false,
                //     file_accept_spreadsheet: false,
                //     file_accept_presentation: false,
                //     file_accept_compressed: false,
                //     checkbox_other_option: false,
                //     radio_other_option: false,
                //     select_multiple: false,
                //     information_icon: null,
                //     order: 11,
                // },
            ],
        };
    },
    template: `
      <questions v-model:questions="questions" :errors="errors" />
    `,
}));
