import { storiesOf } from "@storybook/vue3";
import Questions from "./index";

storiesOf("Questions", module).add("Questions!", () => ({
    components: { Questions },
    data() {
        return {
            errors: {
                1463: "this field is required",
            },
            questions: [{
                    id: 1522,
                    type: "number",
                    required: true,
                    label: "Nesciunt ad molestiae quia.",
                    information: "Earum praesentium illum sint unde in. Quaerat non omnis nemo officia quia aut dicta.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: 6,
                    numberMin: 5,
                    numberMax: 410,
                    numberStepCount: 7,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 1,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 1523,
                    type: "radio",
                    required: true,
                    label: "Ut aut dolorem tenetur nulla.",
                    information: "Laboriosam eaque ut aut id odit. Quam ducimus sed similique. Odio voluptas autem velit vel.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 2,
                    fieldableId: [1],
                    eventFormFieldOptions: [{
                            id: 8893,
                            label: "Pariatur neque repellat alias.",
                            checked: false,
                            order: 1,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8894,
                            label: "Voluptatem illo.",
                            checked: false,
                            order: 2,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8895,
                            label: "Ab minus non est amet.",
                            checked: true,
                            order: 3,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8896,
                            label: "Consequuntur ut sed.",
                            checked: true,
                            order: 4,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8897,
                            label: "Soluta dolor qui id aut.",
                            checked: true,
                            order: 5,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8898,
                            label: "Qui accusamus sit unde et.",
                            checked: true,
                            order: 6,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8899,
                            label: "Optio ratione est magni ipsa.",
                            checked: false,
                            order: 7,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8900,
                            label: "Illo qui suscipit.",
                            checked: false,
                            order: 8,
                            eventFormFields: [],
                            value: [],
                        },
                    ],
                    value: null,
                },
                {
                    id: 1524,
                    type: "textarea",
                    required: false,
                    label: "Dolorem aut hic omnis magni.",
                    information: "Harum nulla dignissimos nulla nostrum. Optio vel nisi et. Rerum autem qui illo.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 7,
                    textareaMinChar: 9,
                    textareaMaxChar: 866,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 3,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 1525,
                    type: "checkbox",
                    required: false,
                    label: "Aliquam ipsam itaque totam.",
                    information: "Accusamus qui quibusdam quisquam adipisci beatae nam. Aut ut cumque ducimus repellendus veniam.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 4,
                    fieldableId: [1],
                    eventFormFieldOptions: [{
                            id: 8901,
                            label: "Dolores accusantium.",
                            checked: true,
                            order: 1,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8902,
                            label: "Sint rerum et quia eius.",
                            checked: true,
                            order: 2,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8903,
                            label: "Illo voluptatem quia.",
                            checked: true,
                            order: 3,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8904,
                            label: "Et vel magnam harum ab.",
                            checked: false,
                            order: 4,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8905,
                            label: "Et veritatis velit distinctio.",
                            checked: true,
                            order: 5,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8906,
                            label: "Dolorem ab eligendi ut unde.",
                            checked: false,
                            order: 6,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8907,
                            label: "Architecto culpa.",
                            checked: true,
                            order: 7,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8908,
                            label: "Est magnam nihil aut.",
                            checked: false,
                            order: 8,
                            eventFormFields: [],
                            value: [],
                        },
                    ],
                    value: null,
                },
                {
                    id: 1526,
                    type: "textarea",
                    required: true,
                    label: "At qui quis commodi.",
                    information: "At voluptas perferendis repudiandae non in officiis et. Voluptas non deserunt voluptatum nihil.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 7,
                    textareaMinChar: 10,
                    textareaMaxChar: 657,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 5,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 1527,
                    type: "textarea",
                    required: false,
                    label: "Et et aliquid autem.",
                    information: "Voluptas quia quae repellat voluptatibus minus exercitationem. Maxime dolor eveniet odio iure.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 7,
                    textareaMinChar: 9,
                    textareaMaxChar: 416,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 6,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 1528,
                    type: "select",
                    required: false,
                    label: "Vitae quae quia voluptatem.",
                    information: "Omnis cupiditate vel ut accusamus totam. Minima unde perspiciatis et numquam dolorem.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 7,
                    fieldableId: [1],
                    eventFormFieldOptions: [{
                            id: 8909,
                            label: "Itaque non maiores quo sunt hic.",
                            checked: false,
                            order: 1,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8910,
                            label: "Rem et dolorem sunt.",
                            checked: true,
                            order: 2,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8911,
                            label: "Itaque aut commodi.",
                            checked: false,
                            order: 3,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8912,
                            label: "Ut omnis est est velit.",
                            checked: true,
                            order: 4,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8913,
                            label: "Iste rerum qui facere illum.",
                            checked: false,
                            order: 5,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8914,
                            label: "Ut eius quia aut.",
                            checked: false,
                            order: 6,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8915,
                            label: "Pariatur ratione.",
                            checked: false,
                            order: 7,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8916,
                            label: "Odio eligendi ea sit.",
                            checked: true,
                            order: 8,
                            eventFormFields: [],
                            value: [],
                        },
                    ],
                    value: null,
                },
                {
                    id: 1529,
                    type: "tel",
                    required: false,
                    label: "Modi aut aut ipsum.",
                    information: "Sed error corporis rerum accusantium. Et quas vel accusantium voluptas. Illo omnis est similique.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 8,
                    fieldableId: [1],
                    value: "(+1) ",
                    eventFormFieldOptions: null,
                },
                {
                    id: 1530,
                    type: "text",
                    required: true,
                    label: "Name Title",
                    information: "",
                    textTransform: null,
                    textMinChar: 1,
                    textMaxChar: 6,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: true,
                    fileAcceptText: true,
                    fileAcceptSpreadsheet: true,
                    fileAcceptPresentation: true,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: "info",
                    order: 9,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 1531,
                    type: "checkbox",
                    required: false,
                    label: "hangi okul",
                    information: "",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 10,
                    fieldableId: [1],
                    eventFormFieldOptions: [{
                            id: 8917,
                            label: "ODTU",
                            checked: true,
                            order: 1,
                            eventFormFields: [{
                                id: 1532,
                                type: "checkbox",
                                required: false,
                                label: "HANGI FAK",
                                information: "",
                                textTransform: null,
                                textMinChar: null,
                                textMaxChar: null,
                                textareaRows: 2,
                                textareaMinChar: null,
                                textareaMaxChar: null,
                                numberInitial: null,
                                numberMin: null,
                                numberMax: null,
                                numberStepCount: 5,
                                fileAcceptImage: false,
                                fileAcceptText: false,
                                fileAcceptSpreadsheet: false,
                                fileAcceptPresentation: false,
                                fileAcceptCompressed: false,
                                checkboxOtherOption: false,
                                radioOtherOption: false,
                                informationIcon: null,
                                order: 1,
                                eventFormFieldOptions: [
                                    { id: 8918, label: "Iktisat", checked: true, order: 1 },
                                    { id: 8919, label: "egitim", checked: false, order: 2 },
                                ],
                            }, ],
                            value: [{
                                id: 1532,
                                type: "checkbox",
                                required: false,
                                label: "HANGI FAK",
                                information: "",
                                textTransform: null,
                                textMinChar: null,
                                textMaxChar: null,
                                textareaRows: 2,
                                textareaMinChar: null,
                                textareaMaxChar: null,
                                numberInitial: null,
                                numberMin: null,
                                numberMax: null,
                                numberStepCount: 5,
                                fileAcceptImage: false,
                                fileAcceptText: false,
                                fileAcceptSpreadsheet: false,
                                fileAcceptPresentation: false,
                                fileAcceptCompressed: false,
                                checkboxOtherOption: false,
                                radioOtherOption: false,
                                informationIcon: null,
                                order: 1,
                                eventFormFieldOptions: [{
                                        id: 8918,
                                        label: "Iktisat",
                                        checked: true,
                                        order: 1,
                                        value: null,
                                    },
                                    {
                                        id: 8919,
                                        label: "egitim",
                                        checked: false,
                                        order: 2,
                                        value: null,
                                    },
                                ],
                                value: null,
                            }, ],
                        },
                        {
                            id: 8920,
                            label: "Option 2",
                            checked: false,
                            order: 2,
                            eventFormFields: [],
                            value: [],
                        },
                    ],
                    value: null,
                },
                {
                    id: 1533,
                    type: "select",
                    required: false,
                    label: "Yasadiginiz sehir",
                    information: "",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 11,
                    fieldableId: [1],
                    eventFormFieldOptions: [{
                            id: 8921,
                            label: "Istanbul",
                            checked: false,
                            order: 1,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 8922,
                            label: "Ankara",
                            checked: false,
                            order: 2,
                            eventFormFields: [{
                                id: 1534,
                                type: "select",
                                required: false,
                                label: "Ilce",
                                information: "",
                                textTransform: null,
                                textMinChar: null,
                                textMaxChar: null,
                                textareaRows: 2,
                                textareaMinChar: null,
                                textareaMaxChar: null,
                                numberInitial: null,
                                numberMin: null,
                                numberMax: null,
                                numberStepCount: 5,
                                fileAcceptImage: false,
                                fileAcceptText: false,
                                fileAcceptSpreadsheet: false,
                                fileAcceptPresentation: false,
                                fileAcceptCompressed: false,
                                checkboxOtherOption: false,
                                radioOtherOption: false,
                                informationIcon: null,
                                order: 1,
                                eventFormFieldOptions: [{
                                        id: 8923,
                                        label: "Cankaya",
                                        checked: false,
                                        order: 1,
                                    },
                                    {
                                        id: 8924,
                                        label: "Yenimahalle",
                                        checked: false,
                                        order: 2,
                                    },
                                ],
                            }, ],
                            value: [{
                                id: 1534,
                                type: "select",
                                required: false,
                                label: "Ilce",
                                information: "",
                                textTransform: null,
                                textMinChar: null,
                                textMaxChar: null,
                                textareaRows: 2,
                                textareaMinChar: null,
                                textareaMaxChar: null,
                                numberInitial: null,
                                numberMin: null,
                                numberMax: null,
                                numberStepCount: 5,
                                fileAcceptImage: false,
                                fileAcceptText: false,
                                fileAcceptSpreadsheet: false,
                                fileAcceptPresentation: false,
                                fileAcceptCompressed: false,
                                checkboxOtherOption: false,
                                radioOtherOption: false,
                                informationIcon: null,
                                order: 1,
                                eventFormFieldOptions: [{
                                        id: 8923,
                                        label: "Cankaya",
                                        checked: false,
                                        order: 1,
                                        value: null,
                                    },
                                    {
                                        id: 8924,
                                        label: "Yenimahalle",
                                        checked: false,
                                        order: 2,
                                        value: null,
                                    },
                                ],
                                value: null,
                            }, ],
                        },
                    ],
                    value: null,
                },
                {
                    id: 1535,
                    type: "textarea",
                    required: true,
                    label: "Multi Line Text",
                    information: "312312312321",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 20,
                    textareaMinChar: 1,
                    textareaMaxChar: 4,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: true,
                    fileAcceptText: true,
                    fileAcceptSpreadsheet: true,
                    fileAcceptPresentation: true,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: "info",
                    order: 12,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 1536,
                    type: "text",
                    required: true,
                    label: "Single Line Text",
                    information: "",
                    textTransform: "uppercase",
                    textMinChar: 1,
                    textMaxChar: 8,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: true,
                    fileAcceptText: true,
                    fileAcceptSpreadsheet: true,
                    fileAcceptPresentation: true,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: "info",
                    order: 13,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 1537,
                    type: "text",
                    required: false,
                    label: "Single Line Text",
                    information: "",
                    textTransform: "capitalize",
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: true,
                    fileAcceptText: true,
                    fileAcceptSpreadsheet: true,
                    fileAcceptPresentation: true,
                    fileAcceptCompressed: false,
                    checkboxOtherOption: false,
                    radioOtherOption: false,
                    informationIcon: "info",
                    order: 14,
                    fieldableId: [1],
                    value: null,
                    eventFormFieldOptions: null,
                },
                {
                    id: 18,
                    type: "select",
                    required: true,
                    label: "Aliquid maiores minima odio.",
                    information: "Ducimus quasi atque neque. In sunt quidem eos sed inventore vel. Quos error et et voluptas.",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 0,
                    fieldableId: [1],
                    eventFormFieldOptions: [{
                            id: 77,
                            label: "Temporibus quis et sed.",
                            checked: false,
                            order: 0,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 78,
                            label: "Corrupti qui sapiente et.",
                            checked: true,
                            order: 56,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 79,
                            label: "Consequuntur qui magni quidem.",
                            checked: false,
                            order: 10,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 80,
                            label: "Amet velit sit ut et.",
                            checked: true,
                            order: 91,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 81,
                            label: "Voluptatem aut numquam qui sunt.",
                            checked: false,
                            order: 38,
                            eventFormFields: [],
                            value: [],
                        },
                        {
                            id: 82,
                            label: "Quasi dolorem sit.",
                            checked: true,
                            order: 1,
                            eventFormFields: [],
                            value: [],
                        },
                    ],
                    value: null,
                },
                {
                    id: 1813,
                    type: "information",
                    required: false,
                    label: "this is a information banner",
                    information: "",
                    text_transform: null,
                    text_min_char: null,
                    text_max_char: null,
                    textarea_rows: 2,
                    textarea_min_char: null,
                    textarea_max_char: null,
                    number_initial: null,
                    number_min: null,
                    number_max: null,
                    number_step_count: 5,
                    file_accept_image: false,
                    file_accept_text: false,
                    file_accept_spreadsheet: false,
                    file_accept_presentation: false,
                    file_accept_compressed: false,
                    radio_other_option: false,
                    select_multiple: null,
                    informationIcon: "info",
                    order: 1,
                    fieldable_id: [],
                },
                {
                    id: 1814,
                    type: "radio",
                    required: false,
                    label: "Single Choice Question",
                    information: "",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    radioOtherOption: true,
                    selectMultiple: null,
                    informationIcon: "info",
                    order: 1,
                    fieldable_id: [143, 144],
                    eventFormFieldOptions: [{
                            id: 9184,
                            label: "Option 1",
                            checked: false,
                            order: 1,
                            eventFormFields: [],
                        },
                        {
                            id: 9185,
                            label: "Option 2",
                            checked: false,
                            order: 2,
                            eventFormFields: [],
                        },
                    ],
                },
                {
                    id: 1824,
                    type: "datepicker",
                    required: true,
                    label: "Date Picker",
                    information: "",
                    text_transform: null,
                    text_min_char: null,
                    text_max_char: null,
                    textarea_rows: 2,
                    textarea_min_char: null,
                    textarea_max_char: null,
                    number_initial: null,
                    number_min: null,
                    number_max: null,
                    number_step_count: 5,
                    file_accept_image: false,
                    file_accept_text: false,
                    file_accept_spreadsheet: false,
                    file_accept_presentation: false,
                    file_accept_compressed: false,
                    radio_other_option: false,
                    information_icon: "info",
                    order: 3,
                    fieldable_id: [143, 144, 264],
                    value: "2021-12-01",
                },
            ],
        };
    },
    template: `
      <questions v-model:questions="questions" :errors="errors" dateFormat="EU" />
    `,
}));