const currencies = [
  {
    symbol: "€",
    code: "EUR",
    title: "Euro",
    precision: 2,
    decimal: ",",
    thousand: ".",
  },
  {
    symbol: "$",
    code: "USD",
    title: "United States Dollar",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "£",
    code: "GBP",
    title: "British Pound",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "₺",
    code: "TRY",
    title: "Turkish Lira",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "AED",
    code: "AED",
    title: "United Arab Emirates Dirham",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "AU$",
    code: "AUD",
    title: "Australian Dollar",
    precision: 2,
    decimal: ".",
    thousand: " ",
  },
  {
    symbol: "R$",
    code: "BRL",
    title: "Brazilian Real",
    precision: 2,
    decimal: ",",
    thousand: ".",
  },
  {
    symbol: "CA$",
    code: "CAD",
    title: "Canadian Dollar",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "CHF",
    code: "CHF",
    title: "Swiss Franc",
    precision: 2,
    decimal: ".",
    thousand: "'",
  },
  {
    symbol: "CN¥",
    code: "CNY",
    title: "Chinese Renminbi Yuan",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "HK$",
    code: "HKD",
    title: "Hong Kong Dollar",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "Rp",
    code: "IDR",
    title: "Indonesian Rupiah",
    precision: 2,
    decimal: ",",
    thousand: ".",
  },
  {
    symbol: "₪",
    code: "ILS",
    title: "Israeli New Sheqel",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "Rs",
    code: "INR",
    title: "Indian Rupee",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "¥",
    code: "JPY",
    title: "Japanese Yen",
    precision: 3,
    decimal: ",",
    thousand: ".",
  },
  {
    symbol: "₩",
    code: "KRW",
    title: "South Korean Won",
    precision: 3,
    decimal: ",",
    thousand: ".",
  },
  {
    symbol: "RM",
    code: "MYR",
    title: "Malaysian Ringgit",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "Nkr",
    code: "NOK",
    title: "Norwegian Krone",
    precision: 2,
    decimal: ",",
    thousand: ".",
  },
  {
    symbol: "NZ$",
    code: "NZD",
    title: "New Zealand Dollar",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "QR",
    code: "QAR",
    title: "Qatari Riyal",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "RUB",
    code: "RUB",
    title: "Russian Ruble",
    precision: 2,
    decimal: ",",
    thousand: ".",
  },
  {
    symbol: "SAR",
    code: "SAR",
    title: "Saudi Riyal",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "SEK",
    code: "SEK",
    title: "Euro",
    precision: 2,
    decimal: ",",
    thousand: " ",
  },
  {
    symbol: "SGD",
    code: "SGD",
    title: "Swedish Krona",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "฿",
    code: "THB",
    title: "Thai Baht",
    precision: 2,
    decimal: ".",
    thousand: ",",
  },
  {
    symbol: "R",
    code: "ZAR",
    title: "South African Rand",
    precision: 2,
    decimal: ".",
    thousand: " ",
  },
];

export function convertCurrencyFormat(currencyCode = "USD") {
  let format = currencies.find((_c) => _c.code === currencyCode.toUpperCase());
  return {
    symbol: format.symbol,
    decimal: format.decimal,
    thousand: format.thousand,
    precision: format.precision,
  };
}
