import { storiesOf } from "@storybook/vue3";
import QuestionValues from "./index";

storiesOf("QuestionValues", module).add("QuestionValues!", () => ({
    data() {
        return {
            questions: [
                { id: 1821, type: "select", label: "Dropdown Menu", value: 9188 },
                {
                    id: 1824,
                    type: "datepicker",
                    label: "Date Picker",
                    value: "2021-12-30",
                },
            ],
            questionSetupData: [{
                    id: 1814,
                    type: "radio",
                    required: false,
                    label: "Single Choice Question",
                    information: "",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    radioOtherOption: true,
                    informationIcon: "info",
                    order: 1,
                    fieldableId: [143, 144],
                    eventFormFieldOptions: [{
                            id: 9184,
                            label: "Option 1",
                            checked: false,
                            order: 1,
                            eventFormFields: [],
                        },
                        {
                            id: 9185,
                            label: "Option 2",
                            checked: false,
                            order: 2,
                            eventFormFields: [],
                        },
                    ],
                },
                {
                    id: 1821,
                    type: "select",
                    required: false,
                    label: "Dropdown Menu",
                    information: "",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    radioOtherOption: false,
                    informationIcon: null,
                    order: 2,
                    fieldableId: [143, 144, 264],
                    eventFormFieldOptions: [{
                            id: 9188,
                            label: "Option 1",
                            checked: false,
                            order: 1,
                            eventFormFields: [],
                        },
                        {
                            id: 9189,
                            label: "Option 2",
                            checked: false,
                            order: 2,
                            eventFormFields: [],
                        },
                    ],
                },
                {
                    id: 1824,
                    type: "datepicker",
                    required: true,
                    label: "Date Picker",
                    information: "",
                    textTransform: null,
                    textMinChar: null,
                    textMaxChar: null,
                    textareaRows: 2,
                    textareaMinChar: null,
                    textareaMaxChar: null,
                    numberInitial: null,
                    numberMin: null,
                    numberMax: null,
                    numberStepCount: 5,
                    fileAcceptImage: false,
                    fileAcceptText: false,
                    fileAcceptSpreadsheet: false,
                    fileAcceptPresentation: false,
                    fileAcceptCompressed: false,
                    radioOtherOption: false,
                    informationIcon: "info",
                    order: 3,
                    fieldableId: [143, 144, 264],
                },
            ],
        };
    },
    components: { QuestionValues },
    template: `
      <QuestionValues :questions="questions" :questionSetupData="questionSetupData" dateFormat="US" />
    `,
}));
