import { storiesOf } from "@storybook/vue3";
import SubmissionPreview from "./index";

storiesOf("SubmissionPreview", module).add("SubmissionPreview!", () => ({
	components: { SubmissionPreview },
	data() {
		return {
			authors: [
				{
					city: "Istanbul",
					country: "TR",
					email: "edmond.stroman@yahoo.com",
					firstname: "Emre Kaan",
					id: 3,
					institution: "MeetingHand",
					isPresenter: false,
					lastname: "Şurgun",
					order: 10,
					phone: "(+1) 697 258 1508",
					title: "Dr",
				},
				// {
				// 	city: "Ernestmouth",
				// 	country: "US",
				// 	email: "grimes.lea@parisian.net",
				// 	firstname: "Vicky",
				// 	id: 2,
				// 	institution: "Hirthe-Heidenreich",
				// 	isPresenter: false,
				// 	lastname: "Weber",
				// 	order: 2,
				// 	phone: "(+1) 1 319 495 1312",
				// 	title: "Assoc Dr.",
				// },
				{
					city: "Istanbul",
					country: "TR",
					email: "edmond.stroman@yahoo.com",
					firstname: "Tolga",
					id: 3,
					institution: "MeetingHand",
					isPresenter: false,
					lastname: "Koç",
					order: 3,
					phone: "(+1) 697 258 1508",
					title: "Dr",
				},
				// {
				// 	email: "benedict.ryan@gmail.com",
				// 	country: "AE",
				// 	firstname: "Otto",
				// 	id: 4,
				// 	isPresenter: false,
				// 	lastname: "Raynor",
				// 	order: 4,
				// 	phone: "(+1) 1 595 712 4907",
				// 	title: "Dr",
				// },
				// {
				// 	city: "West Stephanyton",
				// 	email: "edmond.stroman@yahoo.com",
				// 	country: "IO",
				// 	firstname: "Will",
				// 	id: 5,
				// 	institution: "Leannon, Torphy and Toy",
				// 	isPresenter: false,
				// 	lastname: "Koch",
				// 	order: 5,
				// 	phone: "(+1) 697 258 1508",
				// 	title: "Dr",
				// },
				// {
				// 	city: "Ankara",
				// 	country: "TR",
				// 	email: "edmond.stroman@yahoo.com",
				// 	firstname: "Fatih Sinan",
				// 	id: 6,
				// 	institution: "MeetingHand",
				// 	isPresenter: false,
				// 	lastname: "Yaman",
				// 	order: 6,
				// 	phone: "(+1) 697 258 1508",
				// 	title: "Dr",
				// },
				// {
				// 	city: "Ankara",
				// 	country: "TR",
				// 	email: "edmond.stroman@yahoo.com",
				// 	firstname: "Ahmet",
				// 	id: 7,
				// 	institution: "Arber",
				// 	isPresenter: false,
				// 	lastname: "Yılmaz",
				// 	order: 7,
				// 	phone: "(+1) 697 258 1508",
				// 	title: "Dr",
				// },
				// {
				// 	city: "Istanbul",
				// 	country: "TR",
				// 	email: "edmond.stroman@yahoo.com",
				// 	firstname: "Tolga",
				// 	id: 3,
				// 	institution: "MeetingHand",
				// 	isPresenter: false,
				// 	lastname: "Koç",
				// 	order: 3,
				// 	phone: "(+1) 697 258 1508",
				// 	title: "Dr",
				// },
				// {
				// 	city: "Istanbul",
				// 	country: "TR",
				// 	email: "edmond.stroman@yahoo.com",
				// 	firstname: "Tolga",
				// 	id: 3,
				// 	institution: "MeetingHand",
				// 	isPresenter: false,
				// 	lastname: "Koç",
				// 	order: 3,
				// 	phone: "(+1) 697 258 1508",
				// 	title: "Dr",
				// },
				// {
				// 	city: "Istanbul",
				// 	country: "TR",
				// 	email: "edmond.stroman@yahoo.com",
				// 	firstname: "Tolga",
				// 	id: 3,
				// 	institution: "MeetingHand",
				// 	isPresenter: true,
				// 	lastname: "Koç",
				// 	order: 1,
				// 	phone: "(+1) 697 258 1508",
				// 	title: "Dr",
				// },
			],
			body: [
				{
					eventSubmissionFieldId: 106,
					value:
						'<p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</strong></p><p><em> Ut consequat risus sed orci ultricies convallis. Integer porttitor l</em></p><p><u>ibero at tincidunt porta. Proin quis iaculis tortor. Suspendisse volutpat turpis diam</u></p><p>, eget ultricies orci rutrum eget. Vivamus vulputate augue ac fermentum viverra. Maecenas l</p><p>uctus lobortis est nec interdum. Sed commodo fringilla massa sit amet pellentesque.Facere quo quis nobi.</p><p><br></p><ol><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </li><li>Ut consequat risus sed orci ultricies convallis. Integer porttitor liber</li><li>o at tincidunt porta. Proin quis iaculis tortor. Suspendisse volutpat turp</li></ol><p><br></p><p><br></p><ul><li>is diam, eget ultricies orci rutrum ege</li><li class="ql-align-right">t. Vivamus vulputate augue ac fermentum viverra. </li><li>Maecenas luctus lobortis est nec interdum. Sed c</li><li>ommodo fringilla massa sit amet pellentesque.</li></ul><p><br></p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut c</p><p><br></p><p class="ql-align-center"><a href="dsa" rel="noopener noreferrer" target="_blank">onsequat risus sed orci ultricies convallis. Integer porttitor libero at</a></p><p><br></p><p class="ql-align-right"> tincidunt porta. Proin quis iaculis tortor. Suspendisse volutpat turpis diam, eget ultricies orci rutrum eget. Vivamus vulputate augue ac fermentum viverra. Maecenas luctus lobortis</p><p class="ql-align-right"><br></p><blockquote class="ql-align-right"> est nec interdum. Sed commodo fringilla massa sit amet pellentesque.</blockquote>',
				},
			],
			keywords: [
				"Donec sit amet maximus justo",
				"Interdum et malesuada fames ac",
				"Sedintellusvitaelacusvenenatisdignissimvitaeaccumsannisi Sedintellusvitaelacusvenenatisdignissimvitaeaccumsannisi Sedintellusvitaelacusvenenatisdignissimvitaeaccumsannisi",
			],
			references: [
				"Lorem ipsumLorem ipsummLorem ipsum Lorem ipsum Lorem ipsum",
				"Lorem ipsum",
				"Lorem ipsum",
			],
		};
	},
	template: `
      <SubmissionPreview type="text" topic="Topic 1" presentationType="Oral" title="Title" :authors="authors" :body="body" :keywords="keywords" :references="references" keywordLabel="buralar hep dutluktu"/>
      <br/>
      <SubmissionPreview type="file" :body="body" :authors="authors" title="Title"/>
    `,
}));
